/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Analyzer;


public class Analyzer {
    public static void main(String[] args) throws Exception {
        // arg[1] is either a filename or a directory

        CompilationEngine ce = new CompilationEngine(args[0]);

        System.out.println(args[0]);


        // foreach file
            // create tokenizer
            // creates a compilationEngine and pass it the tokenizer instance to write to an xml file

    }
}
