/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Analyzer;


import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class Analyzer {

    private static List<String> textFiles(String directory) {
        List<String> textFiles = new ArrayList<String>();
        File dir = new File(directory);
        for (File file : dir.listFiles()) {
            if (file.getName().endsWith((".jack"))) {
                textFiles.add(file.getName());
            }
        }
        return textFiles;
    }

    public static void main(String[] args) throws Exception {
        // arg[1] is either a filename or a directory

        List<String> jackFiles = textFiles("/Users/francois.stiennon/Desktop/nand2tetris2/GitHub/Analyzer/src/main/java/Analyzer/Jack/");

        for(String fileName : jackFiles) {
            System.out.println(fileName);
            new CompilationEngine(fileName);
        }

        // foreach file
            // create tokenizer
            // creates a compilationEngine and pass it the tokenizer instance to write to an xml file

    }
}
