/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Analyzer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Analyzer classUnderTest = new Analyzer();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
